name: Package

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: --max_old_space_size=6144

jobs:
  check-package-json:
    name: Package.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Package
        run: pnpm package:json
  check-package-lockfile:
    name: Lockfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Lockfiles
        run: pnpm package:lockfile
  directus_loads_start:
    name: Loads into Directus
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Install dependencies
        shell: bash
        run: pnpm install
  directus_loads_latest:
    needs: directus_loads_start
    runs-on: ubuntu-latest
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Install dependencies
        shell: bash
        run: pnpm install
      - name: Loads into Directus:latest
        run: pnpm package:directus-load
  directus_loads_11:
    needs: directus_loads_start
    runs-on: ubuntu-latest
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Install dependencies
        shell: bash
        run: pnpm install
      - name: Loads into Directus:11
        run: pnpm package:directus-load 11
  directus_loads_10:
    needs: directus_loads_start
    runs-on: ubuntu-latest
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Install dependencies
        shell: bash
        run: pnpm install
      - name: Loads into Directus:10
        run: pnpm package:directus-load 10
